version: 2
jobs:
  test:
    docker:
      - image: cimg/base:edge-20.04
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
workflows:
  version: 2
  build-master:
    jobs:
      - test
