version: 2.1
orbs: 
    snyk: snyk/snyk@0.0.8
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
  publish-latest:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t abberadhi/microblog -f docker/Dockerfile_prod .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push abberadhi/microblog:latest
  deploy-latest:
    machine:
      image: "ubuntu-1604:202007-01"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            make install
            make install-deploy
            pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
      - run:
          name: Run appServer playbook
          command: |
            . .venv/bin/activate
            cd ansible
            ansible-playbook -vvv gather_vm_instances.yml appServer.yml
  snyk:
    machine:
      image: "ubuntu-1604:202007-01"
    steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              python3 -m venv .venv
              . .venv/bin/activate
              make install
              make install-deploy
        - run: echo "source .venv/bin/activate" >> $BASH_ENV # här gör vi så att så att CircleCi automatisk laddar venv och då kollar Snyk vad vi har installerat i den.
        - snyk/scan

workflows:
  version: 2
  build-master:
    jobs:
      - test
      - snyk
      - publish-latest:
          requires:
            - test
      - deploy-latest:
          requires:
            - publish-latest
