version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14.17.3-buster-browsers
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Run test
          command: docker --version
workflows:
  version: 2
  build-master:
    jobs:
      - test
