version: 2
jobs:
  test:
    docker:
      image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Run test
          command: docker --version
workflows:
  version: 2
  build-master:
    jobs:
      - test
