version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Run test
          command: sudo docker-compose up test
workflows:
  version: 2
  build-master:
    jobs:
      - test
