version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run:
          name: Run test
          command: docker --version
workflows:
  version: 2
  build-master:
    jobs:
      - test
