version: 2
executors:
  docker-publisher:
    docker:
      - image: cimg/base:2021.04

jobs:
  test:
    executor: docker-publisher
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
workflows:
  version: 2
  build-master:
    jobs:
      - test
