version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: ubuntu:latest
    docker:
      - image: ubuntu-1604:202007-01
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t gufo19:latest .
            docker-compose up test