version: 2
jobs:
  test:
    machine:
      image: ubuntu-1604:202007-01
    steps:
      # - checkout
      - run:
          name: Run test
          command: docker --version
workflows:
  version: 2
  build-master:
    jobs:
      - test
