version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: gufo19/microblog
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t gufo19:latest .
          docker-compose up test