version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
  publish-latest:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t microblog:latest -f docker/Dockerfile_prod .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push abberadhi/microblog:latest

workflows:
  version: 2
  build-master:
    jobs:
      - test
      - publish-latest:
          requires:
            - test
