version: 2
jobs:
  test:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Run test
          command: docker-compose up test
  publish-latest:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker build -t abberadhi/microblog -f docker/Dockerfile_prod .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push abberadhi/microblog:latest
  deploy-latest:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv .venv
            .venv/bin/python -m pip install --upgrade pip
            .venv/bin/pip3 install -r requirements.txt
            source .venv/bin/activate
      - run:
          name: Activate venv
          command: echo "source .venv/bin/activate" >> $BASH_ENV

      - run:
          name: Deploy latest docker image to appServer
          command: |
            . .venv/bin/activate
            ansible-playbook -vvv ansible/gather_vm_instances.ymlm # ansible/appServer.yml

workflows:
  version: 2
  build-master:
    jobs:
      - test
      - publish-latest:
          requires:
            - test
      - deploy-latest:
          requires:
            - publish-latest
