---
-   name: create new mysql user
    shell: sudo docker exec -it dbserver mysql -uroot -p'secret' -e "CREATE USER 'exporter'@'%' IDENTIFIED BY 'secret' WITH MAX_USER_CONNECTIONS 3;GRANT PROCESS,REPLICATION CLIENT,SELECT ON *.* TO 'exporter'@'%';GRANT SELECT ON performance_schema.* TO 'exporter'@'%';FLUSH PRIVILEGES;"

-   name: start and create mysqld-exporter
    docker_container:
      name: mysqld-exporter
      image: prom/mysqld-exporter:latest
      restart_policy: always
      env:
        DATA_SOURCE_NAME="exporter:secret@(localhost:3306)/"
      command: [
        "--collect.global_status=true",
        "--collect.global_variables=false",
        "--collect.slave_status=false",
        "--collect.info_schema.tables=false",
        "--collect.binlog_size=false",
        "--collect.info_schema.processlist=false",
        "--collect.info_schema.userstats=false",
        "--collect.info_schema.tables=false",
        "--collect.auto_increment.columns=false",
        "--collect.info_schema.tablestats=false",
        "--collect.perf_schema.file_events=false",
        "--collect.perf_schema.eventsstatements=false",
        "--collect.perf_schema.indexiowaits=false",
        "--collect.perf_schema.tableiowaits=false",
        "--collect.perf_schema.tablelocks=false",
        "--collect.perf_schema.eventswaits=false"
      ]
      ports:
        - "9104:9104"